# Build Stage
FROM node:22-alpine AS builder
WORKDIR /app
COPY . .
RUN apk update && apk upgrade && npm install
RUN npm run build

# Production Stage
FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
