# ---------- Stage 1: Build the JAR ----------
FROM maven:3.9.6-eclipse-temurin-17 AS builder
WORKDIR /app

# Copy entire Spring Boot project
COPY . .

# Build the JAR (skip tests for faster build)
RUN mvn clean package -DskipTests

# ---------- Stage 2: Run the JAR ----------
FROM eclipse-temurin:17-jre-jammy
WORKDIR /app

# Copy the JAR file from the builder stage
COPY --from=builder /app/target/medtracker-0.0.1-SNAPSHOT.jar app.jar

# Run the Spring Boot app
ENTRYPOINT ["java", "-jar", "app.jar"]
